### ISSUE TITLE
Better handling of unkown inputs

### ISSUE THREAD

**Issue by marceloschreiber** [CarnunMP/Advent-of-Code#1]
I was looking around for an elegant solution for today's problem and I this is the best I saw.

I just want to point that the current code treats unknow input as files:

```clojure
;; Current code
(defn dispatch-parse-line* [_loc [a b & _args]]
  (cond
    (= "$" a) [:command b]
    (= "dir" a) [:dir]
    :else [:file]))

;; Maybe better
(defn dispatch-parse-line* [_loc line]
  (let [[a b & _args] line]
    (cond
      (= "$" a) [:command b]
      (= "dir" a) [:dir]
      (and (parse-long a) (string? b)) [:file]
      :else line)))
```

Thanks for posting! I wasn't familiar with `zip` and `walk`. They're awesome!

**Comment by carnundotcom** [comment]
Hey! Just now seeing this... nearly two years later. :see_no_evil:

I suppose you're talking about [y2022/d7.clj](https://github.com/CarnunMP/Advent-of-Code/blob/master/src/y2022/d7.clj)? Glad you got something from it! `zip` and `walk` are indeed awesome.

Hard to say, at a glance, whether the guard you propose is necessary. Certainly in a more real-world scenario, I'd want to do this sort of thing! But with AoC problems I like to enjoy the luxury of not having to deal with dirty input data. :)

**Comment by carnundotcom** [comment]
By the way @marceloschreiber, if you're playing along in Clojure again this year, do check out the [#adventofcode Clojurians Slack channel](https://clojurians.slack.com/archives/C0GLTDB2T)!
